### ISSUE TITLE
Is this an assignment?

### ISSUE THREAD

**Issue by AliHaider20** [paisoncodes/ALG_assignment#1]
Just opened to ask if this is an assignment or others can also contribute to this.
If others can contribute plz assign the task to me.

**Comment by paisoncodes** [comment]
Hello Ali,

Yes, it is.

I was working on the assignment and got through the data analysis but I was
stuck with the research analysis.

I would have loved to continue the assignment and get the job but I still
have little experience on research analysis. I'm willing to learn if I find
a mentor also.

Thank you.

**Comment by AliHaider20** [comment]
How much time is left for the assignment deadline? For Data Analysis you should always use jupyter notebook.
Jupyter Notebook features:

1. Can add Heading.
2. Separate cells for running code.

That most important is the expressibility of the code.
.py is only used for production-level code. However, after writing code in Jupyter you can download it in .py.


I don't know what you're pointing out as research analysis, I guess you're telling about Domain knowledge. If it is the case you should read about the college first whose dataset is given. 
Then you should just apply basic pandas methods like df.describe(), df.isna().sum().
Also, you can do numerical and categorical analysis using many plotting functions from matplotlib library.

Let me if any other help is needed.

**Comment by paisoncodes** [comment]
The deadline has passed

**Comment by AliHaider20** [comment]
Then if you assign me this project I would contribute somewhat. Also, you will learn with me and I'll learn from you. This is what Github is all about.

**Comment by paisoncodes** [comment]
Okay.

Do you need the link to the data set and questions?

**Comment by AliHaider20** [comment]
Dataset set is already there. Just send the questions. Also, assign this issue after sending the questions.

**Comment by paisoncodes** [comment]
The assignment is attached below

**Comment by AliHaider20** [comment]
Where I can't find it.

**Comment by paisoncodes** [comment]
It's an attachment

**Comment by AliHaider20** [comment]
I don't know how to find the attachment.

**Comment by paisoncodes** [comment]
Are you opening this message on your mail or on GitHub?

**Comment by AliHaider20** [comment]
On Github as well as on Gmail I'm unable to find it.

**Comment by paisoncodes** [comment]
You're not seeing the PDF file?

**Comment by AliHaider20** [comment]
No.

**Comment by paisoncodes** [comment]
This is it again

**Comment by AliHaider20** [comment]
Sry bro. Can't find it. If you can upload in your rep then it would be great.

**Comment by paisoncodes** [comment]
I already sent it to the repo

**Comment by AliHaider20** [comment]
Thanks for sharing in repo. Below are my feedbacks.
Task1 - I haven't done any task like this but will try once I get time.
Task2 - I have made a project on data analysis.
Task3 -  I guess you have done it already. Am I right?

**Comment by paisoncodes** [comment]
The issue there is the task 1

**Comment by paisoncodes** [comment]
I can handle the rest perfectly

**Comment by AliHaider20** [comment]
I guess the company is a startup company and wants to build and help buildings more jobs in African. I guess the main objective is to find information about the job market like job descriptions of the listed jobs and also they wanted is to find questions and answer them.

**Comment by paisoncodes** [comment]
Yeah, I think so, but I had limited time so. I just stopped working on it

**Comment by AliHaider20** [comment]
Actually, you should work on it. It will improve your Github profile.

**Comment by paisoncodes** [comment]
I will, thanks

**Comment by paisoncodes** [comment]
Do you write django?

**Comment by AliHaider20** [comment]
No. I have plans to learn that.
